### ISSUE TITLE
Some Basic components needs to be patched to be Enhanced components

### ISSUE THREAD

**Issue by marcusedwards-cp** [Crownpeak/DXM-SDK-Core#40]
In the "Basic" components available for drag-and-drop, some of the components have not been patched to provide JSON, i.e. converted to be extended components. These are:

* Code: produces a 'Markup' JSON element but has null for its field values;
* Video: produces a 'Video' JSON element but has null for its field values;

**Comment by richard-lund** [comment]
Code, Color and Video components updated awaiting next release.
