### ISSUE TITLE
Add Component Placeholder Support for CMS Preview

### ISSUE THREAD

**Issue by ptylr** [Crownpeak/DXM-SDK-Core#7]
Used where there is no useful preview for a Component in CMS.

**Comment by richard-lund** [comment]
This can be used to solve issues where uncompiled React, Vue or Angular pre-processor markup gets passed into the CMS. Proposed solution:

`
<! -- cp-scaffold
{field:Text}
/cp-scaffold -->
`

This is standalone markup that will be sent to the Component Library directly, with nothing rendered to the compiled application.

`<! -- cp-scaffold
{field:Text}
else -->
<span @click="something" @mouseover="hover" @mouseout="hoverout">Test</span>
<! -- /cp-scaffold -->
`

This will upload the field to the Component Library, but display the <span> inside the compiled application.

Note comments should be real HTML comments but get mangled by this editor.
